/**
 * Large Document Performance Tests - government template variant (issue #1006)
 *
 * This suite covers large RFP/template-like DOCX files that are not merely
 * high-word-count documents. The synthetic fixture stresses sections, repeated
 * headers, bookmarks, fields, hyperlinks, numbered paragraphs, SDTs, and tables.
 *
 * Uses a synthetic fixture generated by
 * scripts/generate-large-doc-issue1006.ts.
 *
 * Run: npx playwright test e2e/tests/performance-large-docs-government-template.spec.ts --timeout=120000 --workers=1
 */
import { test, expect, Page } from '@playwright/test';
import { EditorPage } from '../helpers/editor-page';
import { recordMetric, writeMetricsIfRequested } from '../helpers/perf-metrics';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const LARGE_DOC_PATH = path.resolve(__dirname, '../fixtures/issue-1006-government-template.docx');
const PERF_SUITE = 'large-docs-government-template';
const MODIFIER = process.platform === 'darwin' ? 'Meta' : 'Control';
const TYPING_AVG_CEILING_MS = 800;
const UNDO_REDO_AVG_CEILING_MS = 1200;

async function loadLargeDoc(page: Page): Promise<void> {
  const fileInput = page.locator('input[type="file"][accept=".docx"]');
  await fileInput.setInputFiles(LARGE_DOC_PATH);
  await page.waitForSelector('[data-page-number]', { timeout: 90_000 });
  await page.waitForTimeout(2000);
}

async function placeCursorOnPage(page: Page, pageNumber: number): Promise<void> {
  const paragraph = page.locator(`[data-page-number="${pageNumber}"] p`).first();
  if ((await paragraph.count()) > 0) {
    await paragraph.click({ position: { x: 50, y: 10 } });
  } else {
    const pageEl = page.locator(`[data-page-number="${pageNumber}"]`);
    const box = await pageEl.boundingBox();
    if (box) {
      await page.mouse.click(box.x + 100, box.y + 100);
    }
  }
  await page.waitForTimeout(300);
}

async function measureKeystrokeLatency(page: Page, key: string = 'a'): Promise<number> {
  const before = performance.now();
  await page.keyboard.press(key);
  await page.evaluate(
    () => new Promise<void>((r) => requestAnimationFrame(() => requestAnimationFrame(() => r())))
  );
  return Math.round(performance.now() - before);
}

async function measureKeystrokes(
  page: Page,
  count: number,
  key: string = 'a'
): Promise<{ latencies: number[]; avg: number; max: number; min: number }> {
  const latencies: number[] = [];
  for (let i = 0; i < count; i++) {
    latencies.push(await measureKeystrokeLatency(page, key));
  }
  const avg = Math.round(latencies.reduce((a, b) => a + b, 0) / latencies.length);
  return { latencies, avg, max: Math.max(...latencies), min: Math.min(...latencies) };
}

async function measureTypingAtPage(
  page: Page,
  pageNumber: number,
  label: string,
  metricPrefix: string,
  options: { placeCursor?: boolean } = {}
): Promise<void> {
  if (options.placeCursor !== false) {
    await placeCursorOnPage(page, pageNumber);
  }

  await page.keyboard.press('x');
  await page.evaluate(
    () => new Promise<void>((r) => requestAnimationFrame(() => requestAnimationFrame(() => r())))
  );

  const stats = await measureKeystrokes(page, 10);
  console.log(
    `${label} typing - avg: ${stats.avg}ms, max: ${stats.max}ms, all: [${stats.latencies.join(', ')}]`
  );
  recordMetric({
    key: `${metricPrefix}.avgMs`,
    label: `${label} typing (avg)`,
    value: stats.avg,
    unit: 'ms',
    direction: 'lower-is-better',
  });
  recordMetric({
    key: `${metricPrefix}.maxMs`,
    label: `${label} typing (max)`,
    value: stats.max,
    unit: 'ms',
    direction: 'lower-is-better',
  });
  expect(stats.avg).toBeLessThan(TYPING_AVG_CEILING_MS);
}

test.describe('Large Document Performance - government template (#1006)', () => {
  test.describe.configure({ timeout: 120_000 });

  let editor: EditorPage;

  test.beforeEach(async ({ page }) => {
    editor = new EditorPage(page);
    await editor.goto();
    await editor.waitForReady();
  });

  test.afterAll(() => {
    writeMetricsIfRequested(PERF_SUITE);
  });

  test('loads structure-heavy government template without crashing', async ({ page }) => {
    const loadStart = Date.now();

    await loadLargeDoc(page);
    const loadTime = Date.now() - loadStart;

    const pageCount = await page.locator('[data-page-number]').count();
    expect(pageCount).toBeGreaterThan(100);
    await expect(page.locator('.ProseMirror').first()).toContainText(
      'Issue 1006 Synthetic Template'
    );

    console.log(`Load time: ${loadTime}ms, Pages: ${pageCount}`);
    recordMetric({
      key: 'load.timeMs',
      label: 'Doc load',
      value: loadTime,
      unit: 'ms',
      direction: 'lower-is-better',
    });
    recordMetric({
      key: 'load.pageCount',
      label: 'Page count',
      value: pageCount,
      unit: 'count',
      direction: 'informational',
    });
  });

  test('typing at document start, middle, and end stays responsive', async ({ page }) => {
    await loadLargeDoc(page);

    await placeCursorOnPage(page, 1);
    await page.keyboard.press(`${MODIFIER}+Home`);
    await page.waitForTimeout(300);
    await measureTypingAtPage(page, 1, 'Start-of-doc', 'typing.start', { placeCursor: false });

    const pageCount = await page.locator('[data-page-number]').count();
    const midPageNum = Math.floor(pageCount / 2);
    await page.evaluate(() => {
      const container =
        document.querySelector('.paged-editor__scroll-container') ||
        document.querySelector('.paged-editor__pages');
      if (container) container.scrollTop = container.scrollHeight / 2;
    });
    await page.waitForTimeout(1500);
    await measureTypingAtPage(page, midPageNum, 'Mid-doc', 'typing.middle');

    await page.evaluate(() => {
      const container =
        document.querySelector('.paged-editor__scroll-container') ||
        document.querySelector('.paged-editor__pages');
      if (container) container.scrollTop = container.scrollHeight;
    });
    await page.waitForTimeout(1500);
    await placeCursorOnPage(page, pageCount);
    await page.keyboard.press(`${MODIFIER}+End`);
    await page.waitForTimeout(300);
    await measureTypingAtPage(page, pageCount, 'End-of-doc', 'typing.end', { placeCursor: false });
  });

  test('undo and redo stay responsive after an edit', async ({ page }) => {
    await loadLargeDoc(page);

    await placeCursorOnPage(page, 1);
    await page.keyboard.press(`${MODIFIER}+Home`);
    await page.waitForTimeout(300);
    await page.keyboard.type('undo test ');
    await page.waitForTimeout(1000);

    const undoStats = await measureKeystrokes(page, 5, `${MODIFIER}+z`);
    const redoStats = await measureKeystrokes(page, 5, `${MODIFIER}+Shift+z`);
    console.log(
      `Undo - avg: ${undoStats.avg}ms, max: ${undoStats.max}ms, all: [${undoStats.latencies.join(', ')}]`
    );
    console.log(
      `Redo - avg: ${redoStats.avg}ms, max: ${redoStats.max}ms, all: [${redoStats.latencies.join(', ')}]`
    );

    recordMetric({
      key: 'undo.avgMs',
      label: 'Undo (avg)',
      value: undoStats.avg,
      unit: 'ms',
      direction: 'lower-is-better',
    });
    recordMetric({
      key: 'redo.avgMs',
      label: 'Redo (avg)',
      value: redoStats.avg,
      unit: 'ms',
      direction: 'lower-is-better',
    });

    expect(undoStats.avg).toBeLessThan(UNDO_REDO_AVG_CEILING_MS);
    expect(redoStats.avg).toBeLessThan(UNDO_REDO_AVG_CEILING_MS);
  });
});
